name: Create Release

# Controls when the action will run.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    # Runner name
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 11
      - run: npm install
      - run: npm run build
      - uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          directory: dist

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}